config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get  'addresses', to: 'users/registrations#address_registration'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'

  namespace :items do
    resources :searches, only: :index
  end
  
  resources :items do
    resources :comments, only: :create

    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
  
    resources :items do
      get "set_parents"
      get "set_children"
      get "set_grandchildren"
      
      get "set_grandzchildren"
      end
  end

    resources :credit_cards, only: [:new, :show, :destroy] do
      collection do
        post 'pay', to: 'credit_cards#pay'
      end
    end

  get "category/set_parents", to: "items#set_parents"
  get "category/set_children", to: "items#set_children"
  get "category/set_grandchildren", to: "items#set_grandchildren"

  resources :users, only: [:show] do
    collection do
      get "log_in"
      get "new_user"
    end
  end

  resources :categories, only: [:show] do
  end

end

app/models/item.rb
class Item < ApplicationRecord
  # active_hash association
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :fee
  belongs_to_active_hash :shipping
  belongs_to_active_hash :condition
  belongs_to_active_hash :prefecture

  # items table association
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :no_image
  def no_image(attributes)
    attributes[:img].blank?
  end

  belongs_to :category
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true

  # validation
  validates :images, presence: true
  validates :name, :detail, :condition_id, :category_id, :price, :fee_id, :prefecture_id, :shipping_id, presence: true

  def self.search(search)
    if search
      Item.where('name LIKE(?) or detail LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController
  def index
    @items = Item.search(params[:keyword]).order('created_at DESC').where("buyer_id is NULL")
    @count = @items.count
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.limit(3).order('created_at DESC').where("buyer_id is NULL")
    @mens_items = Item.where(category_id: 196..326).limit(3).order('created_at DESC').where("buyer_id is NULL")
    @ladies_items = Item.where(category_id: 1..195).limit(3).order('created_at DESC').where("buyer_id is NULL")
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "登録が完了しました"
    else
      @item.images.new
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
    if @item.images.count <= 9
      @item.images.build
    end
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    if @item.seller_id == current_user.id
      if @item.update(item_params)
        redirect_to item_path(@item.id), notice: '商品を更新しました'
      else
        redirect_to edit_item_path, notice: '更新に失敗しました'
      end
    else
      redirect_to item_path(@item.id)
    end
  end

  def destroy
    unless @item.seller_id == current_user.id && @item.destroy
      redirect_to item_path(params[:id])
    end
  end

  def set_parents
    @parents  = Category.where(ancestry: nil)
  end

  def set_children
    @children = Category.where(ancestry: params[:parent_id])
  end

  def set_grandchildren
    @grandchildren = Category.where('ancestry LIKE ?', "%/#{params[:child_id]}")
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :category_id, :condition_id, :fee_id, :prefecture_id, :shipping_id, :price, :brand, images_attributes: [:img,:_destroy,:id]).merge(seller_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items/searches_helper.rb
module Items::SearchesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_app-banner.html.haml
.app-banner
  .app-banner__inner
    %h1.app-banner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.app-banner__inner__text
      今すぐ無料ダウンロード！
  .app-banner__app-btn
    = link_to "#" do
      = image_tag asset_path("app-store.svg"), size: "180x54", alt: "ICON" 
    = link_to "#" do
      = image_tag asset_path("google-play.svg"), size: "180x54", alt: "ICON" 

app/views/items/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAについて
      %ul
        %li
          =link_to "#" do
            会社概要（運営会社）
          =link_to "#" do
            プライバシーポリシー
          =link_to "#" do
            FURIMA利用規約                 
          =link_to "#" do
            ポイントに関する特約 
    %li.footer__contents__content       
      %h2.footer__contents__content__head
        FURIMAを見る
      %ul
        %li
          =link_to "#" do
            カテゴリー一覧
          =link_to "#" do
            ブランド一覧
    %li.footer__contents__content        
      %h2.footer__contents__content__head
        ヘルプ＆ガイド
      %ul
        %li
          =link_to "#" do
            FURIMAガイド
          =link_to "#" do
            FURIMAロゴ利用ガイドライン
          =link_to "#" do
            お知らせ                                          
  
  .footer__log
    = link_to "#" do
      = image_tag asset_path("logo-white.svg"), size: "160x47", alt: "ICON" 
    %p
      © FURIMA

app/views/items/_form.html.haml
.content
  .content__main 
    = form_with model: @item, local: true do |f|
      = render 'layouts/error_messages', model: f.object

      .content__main__item-image-box
        .text-bold
          出品画像
          %span.required
            必須
        最大10枚までアップロードできます
        %br
        #image-box
          #previews
            - if @item.persisted?
              = @item.images.each_with_index do |image, i|
                = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
          = f.fields_for :images do |image|
            %div{data: { index: "#{image.index}" }, class: "review-file_group" }
              = image.file_field :img, class: "item-file"
              %br
                %span.preview-remove
                  削除
            - if @item.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
      .content__main__item-name-box
        .text-bold
          商品名
          %span.required
            必須
        = f.text_field :name, class:"content__main__item-name-box__item-name-field", placeholder: "40文字まで", maxlength: 40
        .text-bold
          商品の説明
          %span.required
            必須
        = f.text_area :detail, class:"content__main__item-name-box__item-exp-field", placeholder: "商品の説明(必須１０００文字以内)\n(色、素材、重さ、定価、注意点など)\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", maxlength: 1000
          
      .content__main__item-info-box
        .content__main__item-info-box__headline
          商品の詳細
        .text-bold
          カテゴリー
          %span.required
            必須
        .jsCategory
          = f.collection_select :category_id, @parents, :id, :name, {prompt: "選択してください"}, class: "content__main__item-info-box__category"
        .text-bold
          ブランド
        = f.text_field :brand, class:"content__main__item-info-box__brand-field", placeholder: "例）シャネル"

        .text-bold
          商品の状態
          %span.required
            必須
        = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, class: "content__main__item-info-box__item-status"

      .content__main__delivery-box
        -# 「配送について」のリンクは削除してもいいかも
        .content__main__delivery-box__headline
          = link_to "#", class: "back-btn" do
            配送について
        .text-bold
          配送料の負担
          %span.required
            必須
        = f.collection_select :fee_id, Fee.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__delivery-fee"
        .text-bold
          発送元の地域
          %span.required
            必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__area"
        .text-bold
          発送までの日数
          %span.required
            必須
        = f.collection_select :shipping_id, Shipping.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__days"

      .content__main__price-box
        .content__main__price-box__headline
          価格(¥300〜9,999,999)
        .content__main__price-box__inner
          .content__main__price-box__inner__left-box
            .text-bold
              販売価格
              %span.required
                必須
          .content__main__price-box__inner__right-box
            = f.number_field :price, class:"content__main__price-box__inner__right-box__price", id: "price-result", min: 300, max: 9999999
        .content__main__price-box__fee-inner
          .content__main__price-box__fee-inner__left
            販売手数料 (10%)
          .content__main__price-box__fee-inner__right
            %span.sall-fee
        .content__main__price-box__profit-inner
          .content__main__price-box__profit-inner__left
            販売利益
          .content__main__price-box__profit-inner__right
            %span.profit
      .content__main__botton-box
        = f.submit "出品する", class: "content__main__botton-box__send-botton"
        -# = f.submit "下書きに保存", class: "content__main__botton-box__draft-botton"
        = link_to root_path, class: "content__main__botton-box__draft-botton", id: "back-btn" do
          もどる

    .content__main__warning-box
      禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/_header.html.haml
.header  
  .header__inner
    .header__inner__main
      %h1.header__inner__main__icon
        = link_to root_path do
          = image_tag asset_path("header_log.svg"), size: "140x41", alt: "ICON" 
      =form_with url: items_searches_path, local: true, class: "header__inner__main__search-box", method: :get do |f|
        .header__inner__main__search-box
          = f.text_field :keyword, class: 'header__inner__main__search-box--text--form', placeholder: 'キーワードから探す'
          = f.button type: :submit, class: "header__inner__main__search-box--submit-btn" do
            = image_tag asset_path("icon-search.svg"), size: "20x20", alt: "ICON"
    .header__inner__nav
      %ul.header__inner__nav__left
        %li.header__inner__nav__left__category
          = link_to "#" do
            カテゴリー
          .header__inner__nav__left__category__box
            = render "categories/header-category"
        %li.header__inner__nav__left__brand
          = link_to "#" do
            ブランド
      %ul.header__inner__nav__right
        -if user_signed_in?
          %li.header__inner__nav__right__login
            = link_to destroy_user_session_path, method: :delete do
              ログアウト
          %li.header__inner__nav__right__new
            = link_to user_path(current_user) do
              マイページ
        -else
          %li.header__inner__nav__right__login
            = link_to new_user_session_path do
              ログイン
          %li.header__inner__nav__right__new
            = link_to new_user_registration_path do
              新規会員登録

app/views/items/_item.html.haml
.content
  %p= item.name
  %p
    = item.price
    円
  - item.images.each do |image|
    = image_tag image.img.url

app/views/items/_main.html.haml
.main
  %section.main__visual
    .main__visual__content
      %h2.main__visual__content__title
        人生を変えるフリマアプリ
      %p.main__visual__content__text      
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main__visual__content__app-btn
        = link_to "#" do
          = image_tag asset_path("app-store.svg"), size: "180x54", alt: "ICON" 
        = link_to "#" do
          = image_tag asset_path("google-play.svg"), size: "180x54", alt: "ICON"   

  %section.main__top-introduction
    %h2.main__top-introduction__title
      FURIMAが選ばれる3つの理由
    %ul.main__top-introduction__lists
      %li.main__top-introduction__lists__list
        .main__top-introduction__lists__list__pict
          %span.main__top-introduction__lists__list__pict__number
            1
          = image_tag asset_path("pict-reason-01.jpg"), alt: "ICON" 
        %h3.main__top-introduction__lists__list__text
          %span
            3分
          ですぐに出品
        %p.main__top-introduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！
      %li.main__top-introduction__lists__list
        .main__top-introduction__lists__list__pict
          %span.main__top-introduction__lists__list__pict__number
            2
          = image_tag asset_path("pict-reason-02.jpg"), alt: "ICON" 
        %h3.main__top-introduction__lists__list__text
          %span
            シンプル
          で使いやすい
        %p.main__top-introduction__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.main__top-introduction__lists__list
        .main__top-introduction__lists__list__pict
          %span.main__top-introduction__lists__list__pict__number
            3
          = image_tag asset_path("pict-reason-03.jpg"), alt: "ICON" 
        %h3.main__top-introduction__lists__list__text
          手数料
          %span
            業界最安
        %p.main__top-introduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！                    

  %section.main__top-app-dl
    .main__top-app-dl__inner
      %h2.main__top-app-dl__inner__title
        会員数日本一位
      %p.main__top-app-dl__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__top-app-dl__inner__app-btn
        = link_to "#" do
          = image_tag asset_path("app-store.svg"), size: "180x54", alt: "ICON" 
        = link_to "#" do
          = image_tag asset_path("google-play.svg"), size: "180x54", alt: "ICON"         
  %section.main__top-key-features
    %h2.main__top-key-features__head
      FURIMAの特徴
    .main__top-key-features__items
      %section.main__top-key-features__items__item
        %figure.main__top-key-features__items__item__image
          = image_tag asset_path("icon-01.svg"), alt: "ICON"
        %h3.figure.main__top-key-features__items__item__title
          簡単に売り買いできる
        %p.figure.main__top-key-features__items__item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.main__top-key-features__items__item
        %figure.main__top-key-features__items__item__image
          = image_tag asset_path("icon-03.svg"), alt: "ICON"
        %h3.figure.main__top-key-features__items__item__title
          売上金は即日振込みに対応
        %p.figure.main__top-key-features__items__item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.main__top-key-features__items__item
        %figure.main__top-key-features__items__item__image
          = image_tag asset_path("icon-04.svg"), alt: "ICON"
        %h3.figure.main__top-key-features__items__item__title
          様々な支払いに対応
        %p.figure.main__top-key-features__items__item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.main__top-pickup-contents
    %h2.main__top-pickup-contents__head
      ピックアップカテゴリ−
    .main__top-pickup-contents__product-box
      .main__top-pickup-contents__product-box__head
        = link_to "#" do
          %h3
            新着アイテム   
      .main__top-pickup-contents__product-box__lists
        -@items.each do |item|
          .main__top-pickup-contents__product-box__lists__list
            = link_to item_path(item.id) do
              %figure.main__top-pickup-contents__product-box__lists__list__image
                = image_tag item.images.find_by(item_id: item.id).img_url, size: "220x150",alt: "ICON", id: "cover"

              .main__top-pickup-contents__product-box__lists__list__body
                .main__top-pickup-contents__product-box__lists__list__body__name
                  %h3
                    = "#{item.name}"
                .main__top-pickup-contents__product-box__lists__list__body__details
                  %ul
                    %li
                      = "#{item.price.to_s(:delimited)}円"
                    %li.main__top-pickup-contents__product-box__lists__list__body__details__link-icon
                      %span
                        ★
                      ０
                  %p
                    (税込)   
    
    .main__top-pickup-contents__product-box
      .main__top-pickup-contents__product-box__head
        = link_to "#" do
          %h3
            レディース新着アイテム   
      .main__top-pickup-contents__product-box__lists
        -@ladies_items.each do |item|
          .main__top-pickup-contents__product-box__lists__list
            = link_to item_path(item.id) do
              %figure.main__top-pickup-contents__product-box__lists__list__image
                = image_tag item.images.find_by(item_id: item.id).img_url, size: "220x150",alt: "ICON", id: "cover"

              .main__top-pickup-contents__product-box__lists__list__body
                .main__top-pickup-contents__product-box__lists__list__body__name
                  %h3
                    = "#{item.name}"
                .main__top-pickup-contents__product-box__lists__list__body__details
                  %ul
                    %li
                      = "#{item.price.to_s(:delimited)}円"
                    %li.main__top-pickup-contents__product-box__lists__list__body__details__link-icon
                      %span
                        ★
                      ０
                  %p
                    (税込) 

    .main__top-pickup-contents__product-box
      .main__top-pickup-contents__product-box__head
        = link_to "#" do
          %h3
            メンズ新着アイテム   
      .main__top-pickup-contents__product-box__lists
        -@mens_items.each do |item|
          .main__top-pickup-contents__product-box__lists__list
            = link_to item_path(item.id) do
              %figure.main__top-pickup-contents__product-box__lists__list__image
                = image_tag item.images.find_by(item_id: item.id).img_url, size: "220x150",alt: "ICON", id: "cover"

              .main__top-pickup-contents__product-box__lists__list__body
                .main__top-pickup-contents__product-box__lists__list__body__name
                  %h3
                    = "#{item.name}"
                .main__top-pickup-contents__product-box__lists__list__body__details
                  %ul
                    %li
                      = "#{item.price.to_s(:delimited)}円"
                    %li.main__top-pickup-contents__product-box__lists__list__body__details__link-icon
                      %span
                        ★
                      ０
                  %p
                    (税込) 

app/views/items/_newpage-button.html.haml
.exhibition-button
  - if user_signed_in?
    = link_to new_item_path, class: "exhibition-button" do
      出品する
      .exhibition-button__camera
        = icon('fas', 'camera')
  - else
    = link_to new_user_session_path, class: "exhibition-button" do
      出品する
      .exhibition-button__camera
        = icon('fas', 'camera')

app/views/items/destroy.html.haml
= render "header"

.succes
  .succes__wall
    .succes__wall__msg
      商品を削除しました。
    .succes__wall__btn
      .succes__wall__btn__mypage
        = link_to user_path(current_user), id: 'mypage' do
          マイページに戻る
      .succes__wall__btn__index
        = link_to root_path, id: 'index' do
          トップページに戻る

= render "footer"

app/views/items/edit.html.haml
= render "header"

.content
  .content__main 
    = form_with model: @item, local: true do |f|
      = render 'layouts/error_messages', model: f.object

      .content__main__item-image-box
        .text-bold
          出品画像
          %span.required
            必須
        最大10枚までアップロードできます
        %br
          #image-box
            #preview
              - @item.images.each_with_index do |image,i|
                - if image.persisted?
                  .preview-box{data: {index:i}, id: "preview-box__#{i}"}
                    .upper-box
                      = image_tag "#{image.img}", data: {index:i}, class: "edit-image", alt: "preview", id: "image-box__#{i}"
                    .lower-box
                      .update-box{data: {index:i}, id: "update-box__#{i}"}
                        %label.edit-btn 編集
                      .delete-box{data: {index:i}, id: "delete-box__#{i}"}
                        %span.delete-btn 削除
                - else
                  %label.add-box{for: "item_images_attributes_#{i}_img", data: {index:i}, id: "add-box__#{i}"}
                    %i.fas.fa-plus
                      %br
                      .add-text
                        画像を追加
                  

            = f.fields_for :images do |image|
              .add_group{data: {index:image.index}}
                = image.file_field :img, class: "hidden-field"
                = image.check_box :_destroy, class: "hidden-destroy"
      .content__main__item-name-box
        .text-bold
          商品名
          %span.required
            必須
        = f.text_field :name, class:"content__main__item-name-box__item-name-field", placeholder: "40文字まで", maxlength: 40
        .text-bold
          商品の説明
          %span.required
            必須
        = f.text_area :detail, class:"content__main__item-name-box__item-exp-field", placeholder: "商品の説明(必須１０００文字以内)\n(色、素材、重さ、定価、注意点など)\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", maxlength: 1000
          
      .content__main__item-info-box
        .content__main__item-info-box__headline
          商品の詳細
        .text-bold
          カテゴリー
          %span.required
            必須
        .jsCategory
          = f.collection_select :category_id, @parents, :id, :name, {prompt: "選択してください", selected: @item.category.parent.parent.id}, class: "content__main__item-info-box__category"
          = f.collection_select :child_id, @category_children_array, :id, :name, {prompt: "選択してください", selected: @item.category.parent.id}, class: "content__main__item-info-box__category", id: "jsChildren_id"
          = f.collection_select :category_id, @category_grandchildren_array, :id, :name, {prompt: "選択してください", selected: @item.category.id}, class: "content__main__item-info-box__category", id: "jsGrandchildren_id"

        .text-bold
          ブランド
        = f.text_field :brand, class:"content__main__item-info-box__brand-field", placeholder: "例）シャネル"

        .text-bold
          商品の状態
          %span.required
            必須
        = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, class: "content__main__item-info-box__item-status"

      .content__main__delivery-box
        -# 「配送について」のリンクは削除してもいいかも
        .content__main__delivery-box__headline
          = link_to "#", class: "back-btn" do
            配送について
        .text-bold
          配送料の負担
          %span.required
            必須
        = f.collection_select :fee_id, Fee.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__delivery-fee"
        .text-bold
          発送元の地域
          %span.required
            必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__area"
        .text-bold
          発送までの日数
          %span.required
            必須
        = f.collection_select :shipping_id, Shipping.all, :id, :name, {prompt: "選択してください"}, class: "content__main__delivery-box__days"

      .content__main__price-box
        .content__main__price-box__headline
          価格(¥300〜9,999,999)
        .content__main__price-box__inner
          .content__main__price-box__inner__left-box
            .text-bold
              販売価格
              %span.required
                必須
          .content__main__price-box__inner__right-box
            = f.number_field :price, class:"content__main__price-box__inner__right-box__price", min: 300, max: 9999999
        .content__main__price-box__fee-inner
          .content__main__price-box__fee-inner__left
            販売手数料 (10%)
          .content__main__price-box__fee-inner__right
            %span.sall-fee
        .content__main__price-box__profit-inner
          .content__main__price-box__profit-inner__left
            販売利益
          .content__main__price-box__profit-inner__right
            %span.profit
      .content__main__botton-box
        = f.submit "出品する", class: "content__main__botton-box__send-botton"
        -# = f.submit "下書きに保存", class: "content__main__botton-box__draft-botton"
        = link_to root_path, class: "content__main__botton-box__draft-botton", id: "back-btn" do
          もどる

    .content__main__warning-box
      禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

= render 'footer'

app/views/items/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "app-banner"
  = render "footer"
  = render "newpage-button"

app/views/items/new.html.haml
%html{lang: "ja"}
  %head
    %meta{charset: "utf-8"}
  %body
    = render "header"
    = render partial: 'form'
    = render "footer"

app/views/items/show.html.haml
= render "header"
.detail-wrapper
  %h1.detail-wrapper__title
    = @item.name
  .detail-wrapper__content
    .detail-wrapper__content__images
      .detail-wrapper__content__images__active
        = image_tag @item.images[0].img.url, class: "detail-wrapper__content__images__active__image"
      - if @item.images[1].present?
        %ul.detail-wrapper__content__images__thumbnail
          - @item.images[1..-1].each do |images|
            %li.detail-wrapper__content__images__thumbnail__list
              = image_tag images.img.url, class: "detail-wrapper__content__images__thumbnail__list__image"
    %table.detail-wrapper__content__table
      %tr
        %td
          出品者
        %th
          = link_to '#', id: 'user' do
            = @item.seller.nickname
      %tr
        %td
          カテゴリー
        %th
          = link_to '#', id: 'category' do
            = @item.category.parent.parent.name
            %br
            %i{class: "fas fa-chevron-right"}
            = @item.category.parent.name
            %br
            %i{class: "fas fa-chevron-right"}
            = @item.category.name
      %tr
        %td
          ブランド
        %th
          = link_to '#', id: 'brand' do
            = @item.brand
      %tr
        %td
          商品の状態
        %th
          = @item.condition.name
      %tr
        %td
          配送料の負担
        %th
          = @item.fee.name
      %tr
        %td
          配送元地域
        %th
          = @item.prefecture.name
      %tr
        %td
          発送の目安
        %th
          = @item.shipping.name

  .detail-wrapper__price
    %span.detail-wrapper__price__icon
      ¥
    %span.detail-wrapper__price__figure
      = @item.price.to_s(:delimited)
    %span.detail-wrapper__price__tax
      (税込み)
    %span.detail-wrapper__price__fee
      送料込み
  .detail-wrapper__btn
    - if @item.buyer_id.present?
      .detail-wrapper__btn__sold
        この商品は売り切れました
    - elsif @item.buyer_id.nil?
      - if user_signed_in? && current_user.id == @item.seller_id
        .detail-wrapper__btn__management
          .detail-wrapper__btn__management__edit
            = link_to edit_item_path(@item.id), id: 'edit' do
              編集する
          .detail-wrapper__btn__management__destroy
            = link_to item_path, id: 'destroy', method: :DELETE do
              商品を削除する
      - elsif user_signed_in?
        .detail-wrapper__btn__buy
          = link_to "#{@item.id}/purchases", id: 'buy' do
            購入する
      - else
        .detail-wrapper__btn__unregist
          商品の購入には
          = link_to new_user_registration_path, id: 'unregist' do
            新規登録
          &thinsp;または&thinsp;
          = link_to new_user_session_path, id: 'unregist' do
            ログイン
          が必要です。
  .detail-wrapper__detail
    %p.detail-wrapper__detail__inner
      = @item.detail
.comment
  .comment__index
    - if @comments.empty?
      .comment__index__yet
        コメントはありません。
    - else
      - @comments.reverse.each do |c|
        .comment__index__content
          .comment__index__content__info
            %p
              %strong
                .comment__index__content__info__user
                  = link_to c.user.nickname, "#"
                .comment__index__content__info__date
                  = c.created_at.strftime("%Y年%m月%d日 %H時%M分")
          .comment__index__content__text
            = c.comment

  .comment__form-wrapper
    - if @item.buyer_id.present?
      .comment__sold
        ー 売り切れた商品にコメントは出来ません ー
    - elsif @item.buyer_id.nil?
    - if user_signed_in?
      .comment__form-wrapper__form
        = form_with model: [@item, @comment], local: true, id: "new_comment" do |f|
          = f.text_area :comment, class: 'comment__form-wrapper__form__text', placeholder: "コメントを入力", rows: "3"
          .comment__form-wrapper__form__msg
            相手のことを考え丁寧なコメントを心がけましょう。
            %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = f.submit "コメントを送信する", class: "comment__form-wrapper__form__btn"
    - else
      .comment__unregist
        コメントの投稿には
        = link_to new_user_registration_path, id: 'unregist' do
          新規登録
        &thinsp;または&thinsp;
        = link_to new_user_session_path, id: 'unregist' do
          ログイン
        が必要です。
= render "footer"