config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get  'addresses', to: 'users/registrations#address_registration'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'

  namespace :items do
    resources :searches, only: :index
  end
  
  resources :items do
    resources :comments, only: :create

    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
  
    resources :items do
      get "set_parents"
      get "set_children"
      get "set_grandchildren"
      
      get "set_grandzchildren"
      end
  end

    resources :credit_cards, only: [:new, :show, :destroy] do
      collection do
        post 'pay', to: 'credit_cards#pay'
      end
    end

  get "category/set_parents", to: "items#set_parents"
  get "category/set_children", to: "items#set_children"
  get "category/set_grandchildren", to: "items#set_grandchildren"

  resources :users, only: [:show] do
    collection do
      get "log_in"
      get "new_user"
    end
  end

  resources :categories, only: [:show] do
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def show
    @category = Category.find(params[:id])
    @items = Item.where(category_id: @category.subtree_ids)
  end
  
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_header-category.html.haml
.category-box
  .parent
    - @parents.each do |parent|
      .parent-content
        = link_to category_path(parent.id) do
          = parent.name
        .child
          - parent.children.each do |child|
            .child-content
              = link_to category_path(child.id) do
                = child.name
              .grandchild
                - child.children.each do |grandchild|
                  .grandchild-content
                    = link_to category_path(grandchild.id) do
                      = grandchild.name

app/views/categories/show.html.haml
= render "items/header"
.categories
  .categories__product-box
    .categories__product-box__head
      = link_to "#" do
        %h3
          = "#{@category.name}の商品一覧"
    .categories__product-box__lists
      - @items.each do |item|
        .categories__product-box__lists__list
          = link_to item_path(item.id) do
            %figure.categories__product-box__lists__list__image
              = image_tag item.images.find_by(item_id: item.id).img_url, size: "220x150",alt: "ICON", id: "cover"
            .categories__product-box__lists__list__body
              .categories__product-box__lists__list__body__name
                %h3
                  = "#{item.name}"
              .categories__product-box__lists__list__body__details
                %ul
                  %li
                    = "#{item.price.to_s(:delimited)}円"
                  %li.categories__product-box__lists__list__body__details__link-icon
                    %span
                      ★
                    ０
                %p
                  (税込)
= render "items/footer"